<?php

namespace ContainerZJxcL1T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CwbwH9qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cwbwH9q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cwbwH9q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'service' => ['privates', '.errored..service_locator.cwbwH9q.App\\Entity\\Service', NULL, 'Cannot autowire service ".service_locator.cwbwH9q": it references class "App\\Entity\\Service" but no such service exists.'],
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'subscriptionRepository' => ['privates', 'App\\Repository\\SubscriptionRepository', 'getSubscriptionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'service' => 'App\\Entity\\Service',
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
            'subscriptionRepository' => 'App\\Repository\\SubscriptionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
