<?php

namespace ContainerJg6NqK8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HecdLmiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hecdLmi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hecdLmi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'subscriptionRepository' => ['privates', 'App\\Repository\\SubscriptionRepository', 'getSubscriptionRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
            'subscriptionRepository' => 'App\\Repository\\SubscriptionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
