<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTvSvm8c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTvSvm8c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTvSvm8c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTvSvm8c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTvSvm8c\App_KernelDevDebugContainer([
    'container.build_hash' => 'TvSvm8c',
    'container.build_id' => 'f9aacdf6',
    'container.build_time' => 1629790587,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTvSvm8c');
