<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZJxcL1T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZJxcL1T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZJxcL1T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZJxcL1T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZJxcL1T\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZJxcL1T',
    'container.build_id' => 'e9797f8f',
    'container.build_time' => 1629693292,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZJxcL1T');
