<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_services_index' => [[], ['_controller' => 'App\\Controller\\ServicesController::index'], [], [['text', '/']], [], []],
    'app_subscription_add' => [[], ['_controller' => 'App\\Controller\\SubscriptionController::add'], [], [['text', '/add']], [], []],
    'app_subscription_delete' => [[], ['_controller' => 'App\\Controller\\SubscriptionController::delete'], [], [['text', '/delete']], [], []],
    'transaction' => [[], ['_controller' => 'App\\Controller\\TransactionController::index'], [], [['text', '/transaction']], [], []],
    'app_transaction_deposit' => [[], ['_controller' => 'App\\Controller\\TransactionController::deposit'], [], [['text', '/deposit']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
